previewsEnabled: true
services:
    plan: free
  - type: web
    name: thespain
    runtime: python
    env: python
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5

databases:
  - name: dpg-ck9c6uf0vg2c73a3s2rg-a
    databaseName: chat_history
    user: chat_history_user